# Generated by Django 5.0.1 on 2024-02-04 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_A', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimension_B', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimension_C', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, choices=[('mm', 'millimeters'), ('cm', 'centimeters'), ('in', 'inches')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateEdited', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=20)),
                ('salesOrder', models.CharField(max_length=20)),
                ('deliveryOrder', models.CharField(max_length=20)),
                ('customerPO', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('pole', models.CharField(max_length=10)),
                ('voltage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canShaftBeTurnedByHand', models.BooleanField()),
                ('isTheYellowShaftCoverInstalled', models.BooleanField()),
                ('isTheWireMeshProvided', models.BooleanField()),
                ('inletCover', models.BooleanField()),
                ('catalogProvided', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(max_length=20)),
                ('has_motor', models.BooleanField(default=False)),
                ('shipmentBatch', models.CharField(blank=True, max_length=20, null=True)),
                ('baseplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.baseplate')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.motor')),
            ],
        ),
        migrations.CreateModel(
            name='Impeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.pump')),
            ],
        ),
    ]
