# Generated by Django 5.0.1 on 2024-02-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_pump_baseplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='baseplate',
        ),
        migrations.AddField(
            model_name='baseplate',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseplate', to='checklist.pump'),
        ),
    ]
