# Generated by Django 5.0.1 on 2024-02-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_impeller_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseplate',
            name='pump',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseplate', to='checklist.pump'),
        ),
        migrations.AlterField(
            model_name='impeller',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.pump'),
        ),
    ]
